nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Api token'
                    name: X-AUTH-TOKEN
                    in: header
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/ad
            - ^/user
            - ^/login
